Books Reducers (Add and Delete)
paulshaun-kdtk/React_Book_Store pull request #3
Opened 2023-09-07 18:41 UTC by paulshaun-kdtk

# CHANGES

- added a created a default list array to display books
- created add books function and button
- created remove books function and button

2023-09-07 19:12 UTC, topeogunleye commented
@paulshaun-kdtk, is this pull request for `use Redux in React components ` project only

2023-09-07 19:50 UTC, paulshaun-kdtk commented
Hi 

Yes it is

2023-09-07 20:05 UTC, topeogunleye requested changes
Hi @paulshaun-kdtk, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
## (Highlights) Good Points: 💪 

🔍 Overall, the student's project fulfills the specified requirements. Here are the highlights and feedback:

✅ The main React component is wrapped with the <Provider> component from react-redux, as required.

✅ The Redux store has been passed into the <Provider>, meeting the requirement.

✅ An initialState has been added to the booksSlice, satisfying the requirement.

✅ The books are accessed from inside the <BookList> component with useSelector, ensuring the correct usage of Redux state.

Adding a book:

✅ The <NewBookForm> component includes a <Button> with an event handler to add a book to the books array, providing the title and author attributes.

✅ The <NewBookForm> component is correctly exported with export default NewBookForm.

Removing a book:
✅ The component responsible for rendering each book (likely <Book>) has a <Button> with an event handler to remove a book from the books array, using the id attribute.
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- For future pull requests, please notice that your branch name `books` does not follow the convention of being named after a feature or action. For example, you could name your branch `added-books`. This makes it easier to track the changes and the purpose of each branch.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 20:05 UTC, topeogunleye commented on src/components/AddBooks.js
> +    const newBook = {
- [ ] Great job, however, please know that it is a requirement for the `<NewBookForm>` component to have a local state for title and author, which is updated through an onChange event. This will enable the user to submit books using the form.

Remember, you're making good progress! Feel free to refer to the provided resources for additional guidance on implementing the necessary methods and relationships. Keep up the good work!

Best regards,
Temitope
Code Reviewer
07/09/2023

2023-09-07 20:05 UTC, topeogunleye commented on src/components/BooksList.js
> +            <button type="button" onClick={() => handleRemoveBook(book.item_id)}>Remove Book</button>
- [ ] Great job implementing the remove button, however, please be informed that the remove book button does not remove the books added i.e it is not working


Remember, you're making good progress! Feel free to refer to the provided resources for additional guidance on implementing the necessary methods and relationships. Keep up the good work!

2023-09-08 08:58 UTC, skyv26 approved these changes
## Hi @paulshaun-kdtk, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDQ4ZGFlNWE1ZjcyNTVmMDg5ODM5ZTAzNTQxNDhiOGM2ZWJjZDJiMCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Prquorv3BhAmFeiNo2/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Professional `README` template ✅ 
- Linters are green ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-13 09:51 UTC, closed without merging